### ISSUE TITLE
Adding Trending Tab

### ISSUE THREAD

**Issue by Henryufa** [CadenHicks/Group_1_Semester_Project#1]
## Goal
We would like users to be able to quickly and easily view the most active repositories in our records.

## Tasks
- [ ] Add trending tab to sidenav
- [ ] Link trending tab in sidenav to new trending page
- [ ] Create trending page with a repo table
- [ ] Query for the top 10 GitHub repos in our records
- [ ] Populate table with these 10 repos and link to their overview page
