### ISSUE TITLE
Add Total Pull Requests to the Table on the Repos Tab

### ISSUE THREAD

**Issue by Henryufa** [CadenHicks/Group_1_Semester_Project#18]
## Goal
We would like users to be able to view the all time pull requests when viewing repos

## Tasks
- [x] Add all time pull requests as a column on the repos page table
- [x] Populate all time pull requests column with accurate information
- [x] Enable sorting of this new column
