### ISSUE TITLE
Add Project Health Description to Repos Page

### ISSUE THREAD

**Issue by Henryufa** [CadenHicks/Group_1_Semester_Project#4]
## Goal
We would like users to be able to get an understanding of the health of each project on the repos page by displaying important health information

## Tasks
- [ ] Determine what information to display to report project health e.g. avg commits last month, number of active contributors, etc.
- [ ] Decide how to display that information e.g. 1-10 score, red-green color, etc.
- [ ] Query health info
- [ ] Create component that can be attached to graphs
- [ ] Add component to graphs and populate it with the info it needs
