### ISSUE TITLE
Add Filter Functionality to Table on Repos Page

### ISSUE THREAD

**Issue by Henryufa** [CadenHicks/Group_1_Semester_Project#5]
## Goal
We would like the user to be able to filter out repos by some characteristics such as most recent commit.

## Tasks
- [ ] Create filter component that allows user to select attribute to filter by e.g. only display repos with 10 or more active contributors or only the repos that have made a commit in the last month.
- [ ] Add component to the table on the repos page
- [ ] Filter repos displayed on the repos page according to the state of the filter component
